services:
  python_app:
    build: .
    container_name: python_app
    ports:
      - "8082:8082"
      - "8443:8443"
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8083:8080"
    depends_on:
      - python_app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
